  name: pp
  channels:
          - conda-forge
          - rpmuller
  dependencies:
          - ipython
          - ipykernel
          - numpy
          - pyquante2
          - pytest
          - pylint
          - autopep8
          - pip
          - pip:
            - pint

          
